version: "3"
services:
  db:
    image: "postgres:15"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=todo
    volumes:
      - ./pgdata:/var/lib/postgresql/data
